# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: skillsunionsaravanan
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: group1
# "service" is the name of this project. This will also be added to your AWS resource names.
service: group1capstoneproject

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
